name: Update Steam News

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */2 * * *'  # Every 2 hours at 15 minutes past the hour

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Fetch Steam news
      id: fetch_news
      run: |
        if python scripts/fetch_steam_news.py; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "News updated successfully"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No new news items found"
        fi
    
    - name: Commit and push changes
      if: steps.fetch_news.outputs.has_changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Add changed files
        git add version-monitor/data/steam_news.json
        
        # Get current timestamp
        TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        
        # Commit with timestamp
        git commit -m "Update Steam news: $TIMESTAMP"
        
        # Push changes
        git push